package com.example.scadvisor.entity;

public enum Tactic {
    TACTIC_ABRIRBANDAS("ABRIR JUEGO A LAS BANDAS"),
    TACTIC_JUEGODETOQUE("JUEGO DE TOQUE"),
    TACTIC_CENTROSALAREA("CENTROS AL AREA"),
    TACTIC_PELOTAZOARRIBA("PELOTAZO ARRIBA"),
    TACTIC_CONTRAATAQUE("JUEGO AL CONTRAATAQUE"),
    TACTIC_TRANSICIONESRAPIDAS("TRANSICIONES RAPIDAS"),
    TACTIC_CENTRALSUBEAREMATAR("CENTRAL SUBE A REMATAR"),
    TACTIC_ULTRAOFENSIVO("ULTRAOFENSIVO"),
    TACTIC_ULTRADEFENSIVO("ULTRADEFENSIVO"),
    TACTIC_PONERELAUTOBUS("PONER EL AUTOBUS");

    private final String name;

    Tactic(String name) {
        this.name = name;
    }

    public String getName(){
        return name;
    }
}
